# This configuration file controls functionalities for Particle Swarm Optimizing invivo MRI data
# anything with (!!!!) behind the description will be implemented within the PSO class directly in future
general:
  PSO_version:      "2.0.0"
source:
  file:
    prj_dir:   'F:/JIMM2/MWF_invivo/DZNE_Data/24_10_10_c/' # project directory 'S:/data_JIMM2_Bonn/24_10_10_c/'
    T1:        'NO_FILE'                     # (not measured in the 2023/2024 sessions)
    T2:        'mese_run1.nii'               # multi echo spin echo
    T2S:       'mege_mag_run1.nii'           # multi echo gradient echo
    CT2S:      'mege_phs_run1.nii'           # T2S phase information
    TE:        'te.npy'                      # 1D-array of TE times
    B1:        'dream_corr_resampled.nii'    # radiofrequency (RF) transmit field
    ATLAS:     'Atlas_Mean.nii'              # atlas of predefined MFW distribution in a brain
  signal:
    T1:        false                         # [True/False]
    T2:        true                          # [True/False]
    T2S:       false                         # [True/False]
    CT2S:      false                         # [True/False]
    SI:        true                          # [True/False]
    JI:        false                         # [True/False]
  data:
    type:       'invivo'                     # ['invivo', 'atlas'] - for now we use only measured data
    add_noise:  [false, 150]                 # [[True/False], level]
    gauss_filt: [false, [1.0,1.0,0]]         # spatial Gaussian smoothing filter using sigma as in [sx,sy,sz]
    norm_max:   true                         # [True/False] - True is default
    shape:      [110, 110, 24]               # [x,y,z] - nifti data array shape; atlas shape: [182, 218, 182]
    atlas:
      axis:    'Z'        # ['X','Y','Z'] axis of interest
      seed:    1          # seed for randomized noise on synthetic data based on 2 Gaussians
      thresh:  0.025      #  MWF threshold for binary PSO mask
      T1:
        mean:  [400,1000] # [m1,m2] for synthetic data based on 2 Gaussians
        width: [0.5,0.5]  # [m1_sig,m2_sig] for synthetic data based on 2 Gaussians
      T2:
        mean:  [20,80]    # [m1,m2] for synthetic data based on 2 Gaussians
        width: [0.5,0.5]  # [m1_sig,m2_sig] for synthetic data based on 2 Gaussians
      T2S:
        mean:  [10,40]    # [m1,m2] for synthetic data based on 2 Gaussians
        width: [0.5,0.5]  # [m1_sig,m2_sig] for synthetic data based on 2 Gaussians
        phase: [-8,0,0.5] # [MW_f, FW_f, phi] for synthetic data based on 2 Gaussians
  mask:
    use:       true                   # [True, False, None]
    seg:       [3,4,5]                # 1.CSF, 2.Gray Matter (GM), 3.White Matter (WM)
                                      # 4.Deep Gray Matter (dGM), 5.Brain Stem (BS), 6.Cerebellum (CB)
    path:      'mask/sgm_se0.nii.gz'  # relative mask path within your project directory 
#
PSO_spec:
  calc:
    performance_test:
      use:   false   # [True/False] - for developer
    calibration_test:
      use:   false   # [True/False] - for developer
    iter_test:
      use:   false   # [True/False]
      slice: 7       # integer of slice to perform test on
      pixli: [[45,45], [30,70]]
      gif:   false   # create a gif from the pixels in the pixel list 'pixli'
    PSO_on_slice:
      use:   true    # [True/False]
      start: 0       # ID [int] of start slice [Note: Python starts indexing by 0]
      end:   24      # ID [int] of end slice (Python syntax: until, but not included)
    PSO_on_pixel:
      use:   false   # [True/False]
      slice: 7       # integer of slice to perform PSO on
      pixel: [50,65] # pixel for data analysis
  algo_math:
    width:  10       # gauss bell width at lim(y)-->0, which can be estimated within error intervall @around 6.5
    batch:  16       # batch size / no curves for calculating GAUSS bells within the model room
    njit:   true     # use / don't use numba njit acceleration
  PSO_math:
    pixel:     [0, 0]    # internal and automatically filled: pixel on which PSO is executed
    rand:      [True, 0] # np.random.seed for comparability of PSO runs with different random init parameters, default=0
    norm:      True      # use / don't use norm to max value for synthetic data curves (recommended)
    lp_norm:   'L2'      # lp-norm used to evaluate the objective function (L1: Manhattan norm, L2: Euclidean norm).
    weights:   [1.0,1.0,1.0] # weighting factors (α, β, γ) for the individual terms of the joint objective function.
    n_iter:    15        # number of iterations during PSO execution
    n_part:    32        # number of particles used for PSO execution; must an integer multiple of the batch site (algo_math)
    n_comp:    2         # [2,3]: 2 components - m1(MW), m2(FW) | 3 components - m1(MW), m2(AW), m3(EW)
    n_mod_vec: 2         # [V0,V1]: number of modelvectors --> V0: 2 & V1: 1
    cyc_slice: 100       # number of cycles of individual PSO executions on a slice
    cyc_pixel: 10000     # number of cycles of individual PSO executions on a pixel